# Generated by Django 4.2 on 2023-10-14 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_limit_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="card",
        ),
        migrations.RemoveField(
            model_name="card",
            name="data",
        ),
        migrations.AddField(
            model_name="card",
            name="card_number",
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="cvv",
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="expiration_date",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
