# Generated by Django 4.2.6 on 2023-10-14 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_cash_managers_userbalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="cash",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.cash"
            ),
            preserve_default=False,
        ),
    ]
