# Generated by Django 4.2 on 2023-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_card_card_remove_card_data_card_card_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summ", models.CharField(max_length=200)),
            ],
        ),
    ]
