# Generated by Django 4.2.6 on 2023-10-15 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_transaction_amount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserBalance",
        ),
    ]
