# Generated by Django 4.2.6 on 2023-10-15 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_delete_userbalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="cash",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.cash"
            ),
            preserve_default=False,
        ),
    ]
