# Generated by Django 4.2.6 on 2023-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
